name: PHPStan CI

on:
  push:
  pull_request:

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: pmmp/setup-php-action@3.2.0
        with:
          php-version: 8.2
          install-path: ./bin

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: php vendor/bin/phpstan.phar analyze --no-progress
